fname = input("Please Enter your First Name: ") 
lname = input("Please Enter your Last Name: ")  
mname = input("Please Enter your Middle Name: ")  
bday = input("Please Enter your Birthday: ")   
gender = input("Please Enter your Gender: ")  
address = input("Please Enter your Address: ")  
course = input("Please Enter your Course: ")  
ylevel = input("Please Enter your Year Level: ")   

print("+++++++++++++++++++++++++++++++++++++++") 
print("First Name: ", fname) 
print("Last Name: ", lname) 
print("Middle Name: ", mname) 
print("Birthday: ", bday) 
print("Gender: ", gender) 
print("Address: ", address) 
print("Course: ", course) 
print("Year Level: ", ylevel) 
print("+++++++++++++++++++++++++++++++++++++++") 
